---
services:
  postgres:
    restart: always
    image: postgres:17.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    restart: always
    build:
      context: .
      dockerfile: backend.Dockerfile
      labels:
        - environment=uat
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - postgres
    environment:
      FLASK_APP:     run.py
      FLASK_DB_TYPE: postgres       # Use postgres
      FLASK_DB_USER: postgres       # Usuário do banco
      FLASK_DB_NAME: postgres       # Nome do Banco
      FLASK_DB_PASSWORD: secretpass # Senha do banco
      FLASK_DB_HOST: postgres       # Hostname
      FLASK_DB_PORT: 5432           # Porta
    networks:
      - backend

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
      labels:
        - environment=uat
    ports:
      - "80:80"
    depends_on:
      - backend 
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend
      - backend

volumes:
  pg_data:

networks:
  frontend:  
  backend: